services:
  - type: web
    name: musicianlearner-basic-pitch
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
